/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Exercice2;

import Exercice1.TimeModelEvent;
import Exercice1.TimeModelListener;
import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author FRS4440A
 */
public class TimePanel extends javax.swing.JPanel implements TimeModelListener {

    /**
     * Creates new form TimePanel
     */
    public TimePanel() {
        initComponents();
    }
    
    @Override
    public void paintComponent (Graphics g) {
        //On fait le super pour ne pas perdre les propriétés du composant, tel que la transparence
        super.paintComponent(g);
        //g.drawOval(this.getHeight()/2,this.getWidth()/2, this.getHeight(), this.getWidth());
        g.setColor(Color.gray);
        g.fillOval(0,0,this.getHeight(),this.getWidth());
        g.setColor(Color.blue);
        g.fillOval(this.getHeight()/2,this.getWidth()/2,10,10);
        g.fillOval(10,this.getWidth()/2, 10, 10);
        g.fillOval(this.getHeight()/2, 10, 10, 10);
        g.fillOval(10,this.getWidth(), 10, 10);
        //utiliser la fonction rotate point pour faire tous les autres points facilement en fonction du centre.
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void timeChanged(TimeModelEvent event) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
